# Generated by Django 5.2 on 2025-08-09 13:01

import socials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0007_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(default='', upload_to='post_media/', validators=[socials.models.validate_media_file]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], default='', max_length=10),
        ),
    ]
