# Generated by Django 5.2 on 2025-08-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0008_remove_post_image_post_media_post_media_type'),
    ]

    operations = [
    ]
