# Generated by Django 5.2 on 2025-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0011_profile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='works_at',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
