# Generated by Django 5.2 on 2025-08-13 22:27

import socials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0012_profile_works_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='post_media/', validators=[socials.models.validate_media_file]),
        ),
    ]
