# Generated by Django 5.2 on 2025-08-18 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0014_profile_cover_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('post_id', 'username')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post_id'], name='socials_com_post_id_5a9b49_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post_id', 'created_at'], name='socials_com_post_id_98660f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['username'], name='socials_com_usernam_366f55_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='socials_fol_followe_32d12e_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='socials_fol_followi_f314d9_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'following'], name='socials_fol_followe_001276_idx'),
        ),
        migrations.AddIndex(
            model_name='likepost',
            index=models.Index(fields=['post_id'], name='socials_lik_post_id_0bccfa_idx'),
        ),
        migrations.AddIndex(
            model_name='likepost',
            index=models.Index(fields=['username'], name='socials_lik_usernam_d7decd_idx'),
        ),
        migrations.AddIndex(
            model_name='likepost',
            index=models.Index(fields=['post_id', 'username'], name='socials_lik_post_id_2cae3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='socials_pos_created_648e56_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='socials_pos_user_id_2fca8d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='socials_pos_user_id_793de4_idx'),
        ),
    ]
