# Generated by Django 5.2.4 on 2025-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='socials.post'),
        ),
    ]
