# Generated by Django 5.2 on 2025-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0017_profile_saved_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
