# Generated by Django 5.2 on 2025-08-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0017_profile_saved_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(default='profile_pics/blank-profile-picture.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
