# Generated by Django 5.2 on 2025-08-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0018_remove_post_media_remove_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media_url',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profilepic',
        ),
    ]
