# Generated by Django 5.2 on 2025-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0018_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='', upload_to='profile_pics/'),
        ),
    ]
