# Generated by Django 5.2 on 2025-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0020_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='https://res.cloudinary.com/dou9magab/image/upload/v1756479692/user2_pd3xii.jpg', upload_to='profile_pics/'),
        ),
    ]
