# Generated by Django to merge conflicting migrations for 'socials'
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0019_rename_media_url_post_media_and_more'),
        ('socials', '0022_alter_post_media_alter_profile_cover_photo_and_more'),
    ]

    operations = []
