# Generated by Django 5.2 on 2025-09-03 17:56

import cloudinary.models
import socials.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0023_merge_0019_rename_media_url_post_media_and_more_0022_alter_post_media_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[socials.models.validate_media_file], verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dou9magab/image/upload/v1756479692/user2_pd3xii.jpg', max_length=255, verbose_name='profilepic'),
        ),
    ]
