# Generated by Django 5.2 on 2025-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0024_alter_post_media_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
